Repository maucon/Battleship, pull requests merged in 2020-08, with the labels that each got.

#16 Validate user input
  src/main/de/twintorx/battleship/console/Message.kt
  src/main/de/twintorx/battleship/game/Player.kt
  src/test/de/twintorx/battleship/InputRegexTest.kt
Labels: enhancement

#15 Prettify console prints
  src/main/de/twintorx/battleship/console/Message.kt
  src/main/de/twintorx/battleship/game/Data.kt
  src/main/de/twintorx/battleship/game/Player.kt
  src/main/de/twintorx/battleship/game/Ship.kt
  src/main/de/twintorx/battleship/game/board/GameBoard.kt
  src/main/de/twintorx/battleship/game/board/TrackBoard.kt
  src/test/de/twintorx/battleship/GameBoardTest.kt
  src/test/de/twintorx/battleship/GameTest.kt
  src/test/de/twintorx/battleship/TrackBoardTest.kt
Labels: feature

#26 Gradle-jar
  .gitignore
  build.gradle
Labels: feature

#23 Github Actions
  .github/workflows/build.yml
  .github/workflows/release.yml
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/test/kotlin/de/twintorx/battleship/ConnectionTest.kt
  src/test/kotlin/de/twintorx/battleship/PlayerTest.kt
Labels: feature

#32 Build readme badge
  .github/workflows/release.yml
  README.md
Labels: feature

#31 Validate and test connect ip
  src/main/kotlin/de/twintorx/battleship/connection/Client.kt
  src/main/kotlin/de/twintorx/battleship/game/Player.kt
Labels: feature

#35 Console color
  build.gradle
  src/main/java/de/twintorx/battleship/Main.java
  src/main/kotlin/de/twintorx/battleship/Main.kt
  src/main/kotlin/de/twintorx/battleship/connection/Server.kt
  src/main/kotlin/de/twintorx/battleship/console/Color.kt
  src/main/kotlin/de/twintorx/battleship/console/Message.kt
  src/main/kotlin/de/twintorx/battleship/console/Writer.kt
  src/main/kotlin/de/twintorx/battleship/game/Data.kt
  src/main/kotlin/de/twintorx/battleship/game/Player.kt
  src/test/kotlin/de/twintorx/battleship/GameBoardTest.kt
  src/test/kotlin/de/twintorx/battleship/GameTest.kt
  src/test/kotlin/de/twintorx/battleship/TrackBoardTest.kt
Labels: bug

#37 Clear class structure
  gradle/wrapper/gradle-wrapper.properties
  src/main/kotlin/de/twintorx/battleship/Main.kt
  src/main/kotlin/de/twintorx/battleship/connection/Client.kt
  src/main/kotlin/de/twintorx/battleship/connection/Server.kt
  src/main/kotlin/de/twintorx/battleship/game/Data.kt
  src/main/kotlin/de/twintorx/battleship/game/board/Cell.kt
  src/main/kotlin/de/twintorx/battleship/game/board/GameBoard.kt
  src/main/kotlin/de/twintorx/battleship/game/board/Grid.kt
  src/main/kotlin/de/twintorx/battleship/game/board/Move.kt
  src/main/kotlin/de/twintorx/battleship/game/board/TrackBoard.kt
  src/main/kotlin/de/twintorx/battleship/game/ship/Ship.kt
  src/main/kotlin/de/twintorx/battleship/game/ship/ShipType.kt
  src/main/kotlin/de/twintorx/battleship/ui/Color.kt
  src/main/kotlin/de/twintorx/battleship/ui/Player.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/InputRegex.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/PlayerMessage.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/ServerMessage.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/Writer.kt
  src/test/kotlin/de/twintorx/battleship/GameBoardTest.kt
  src/test/kotlin/de/twintorx/battleship/GameTest.kt
  src/test/kotlin/de/twintorx/battleship/InputRegexTest.kt
  src/test/kotlin/de/twintorx/battleship/TrackBoardTest.kt
Labels: change

#39 Player disconnect
  src/main/kotlin/de/twintorx/battleship/connection/Client.kt
  src/main/kotlin/de/twintorx/battleship/connection/Server.kt
  src/main/kotlin/de/twintorx/battleship/ui/Player.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/PlayerMessage.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/ServerMessage.kt
Labels: bug, feature

#41 Player messages
  src/main/kotlin/de/twintorx/battleship/connection/Client.kt
  src/main/kotlin/de/twintorx/battleship/connection/Server.kt
  src/main/kotlin/de/twintorx/battleship/ui/Player.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/PlayerMessage.kt
Labels: change

#44 Clickable jar
  src/main/kotlin/de/twintorx/battleship/Main.kt
Labels: change

#43 Delete console prints
  src/main/kotlin/de/twintorx/battleship/connection/Server.kt
  src/main/kotlin/de/twintorx/battleship/game/board/Cell.kt
  src/main/kotlin/de/twintorx/battleship/ui/Player.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/InputRegex.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/PlayerMessage.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/ServerMessage.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/Writer.kt
  src/test/kotlin/de/twintorx/battleship/GameBoardTest.kt
Labels: feature

#50 Ship rework
  src/main/kotlin/de/twintorx/battleship/game/Ship.kt
  src/main/kotlin/de/twintorx/battleship/game/board/Cell.kt
  src/main/kotlin/de/twintorx/battleship/game/board/GameBoard.kt
  src/main/kotlin/de/twintorx/battleship/game/board/Grid.kt
  src/main/kotlin/de/twintorx/battleship/game/board/TrackBoard.kt
  src/main/kotlin/de/twintorx/battleship/game/cell/Cell.kt
  src/main/kotlin/de/twintorx/battleship/game/cell/Mark.kt
  src/main/kotlin/de/twintorx/battleship/game/ship/Ship.kt
  src/main/kotlin/de/twintorx/battleship/game/ship/ShipType.kt
  src/main/kotlin/de/twintorx/battleship/ui/Player.kt
  src/test/kotlin/de/twintorx/battleship/GameBoardTest.kt
  src/test/kotlin/de/twintorx/battleship/GameTest.kt
  src/test/kotlin/de/twintorx/battleship/TrackBoardTest.kt
Labels: rework

#59 Custom port
  src/main/kotlin/de/twintorx/battleship/connection/Client.kt
  src/main/kotlin/de/twintorx/battleship/connection/Server.kt
  src/main/kotlin/de/twintorx/battleship/ui/Player.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/InputRegex.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/PlayerMessage.kt
  src/test/kotlin/de/twintorx/battleship/InputRegexTest.kt
Labels: feature

#53 Mark last shot
  src/main/kotlin/de/twintorx/battleship/game/board/GameBoard.kt
  src/main/kotlin/de/twintorx/battleship/game/board/TrackBoard.kt
  src/main/kotlin/de/twintorx/battleship/game/cell/Mark.kt
  src/main/kotlin/de/twintorx/battleship/ui/Player.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/PlayerMessage.kt
  src/test/kotlin/de/twintorx/battleship/GameBoardTest.kt
  src/test/kotlin/de/twintorx/battleship/GameTest.kt
  src/test/kotlin/de/twintorx/battleship/InputRegexTest.kt
  src/test/kotlin/de/twintorx/battleship/TrackBoardTest.kt
Labels: feature

#62 changed server-client connection
  src/main/kotlin/de/twintorx/battleship/connection/Client.kt
  src/main/kotlin/de/twintorx/battleship/connection/ClientSocket.kt
  src/main/kotlin/de/twintorx/battleship/connection/Package.kt
  src/main/kotlin/de/twintorx/battleship/connection/Server.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/ServerMessage.kt
Labels: rework

#52 Ship counter
  src/main/kotlin/de/twintorx/battleship/game/Ship.kt
  src/main/kotlin/de/twintorx/battleship/game/board/TrackBoard.kt
  src/main/kotlin/de/twintorx/battleship/ui/Player.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/PlayerMessage.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/Writer.kt
Labels: feature

#66 Last hit mark
  src/main/kotlin/de/twintorx/battleship/game/board/TrackBoard.kt
  src/main/kotlin/de/twintorx/battleship/game/cell/Mark.kt
  src/main/kotlin/de/twintorx/battleship/ui/Player.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/PlayerMessage.kt
  src/test/kotlin/de/twintorx/battleship/GameBoardTest.kt
  src/test/kotlin/de/twintorx/battleship/TrackBoardTest.kt
Labels: change

#67 Win screen
  src/main/kotlin/de/twintorx/battleship/connection/Client.kt
  src/main/kotlin/de/twintorx/battleship/connection/Server.kt
  src/main/kotlin/de/twintorx/battleship/game/Ship.kt
  src/main/kotlin/de/twintorx/battleship/game/board/GameBoard.kt
  src/main/kotlin/de/twintorx/battleship/game/board/Grid.kt
  src/main/kotlin/de/twintorx/battleship/game/board/TrackBoard.kt
  src/main/kotlin/de/twintorx/battleship/game/cell/Cell.kt
  src/main/kotlin/de/twintorx/battleship/game/cell/Mark.kt
  src/main/kotlin/de/twintorx/battleship/ui/Console.kt
  src/main/kotlin/de/twintorx/battleship/ui/Player.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/PlayerMessage.kt
Labels: feature

#70 Ship placement
  src/main/kotlin/de/twintorx/battleship/ui/Player.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/PlayerMessage.kt
Labels: feature

#69 Release v1.1
  .github/workflows/release.yml
  src/main/kotlin/de/twintorx/battleship/Main.kt
  src/main/kotlin/de/twintorx/battleship/connection/Client.kt
  src/main/kotlin/de/twintorx/battleship/connection/ClientSocket.kt
  src/main/kotlin/de/twintorx/battleship/connection/Package.kt
  src/main/kotlin/de/twintorx/battleship/connection/Server.kt
  src/main/kotlin/de/twintorx/battleship/game/Ship.kt
  src/main/kotlin/de/twintorx/battleship/game/board/Cell.kt
  src/main/kotlin/de/twintorx/battleship/game/board/GameBoard.kt
  src/main/kotlin/de/twintorx/battleship/game/board/Grid.kt
  src/main/kotlin/de/twintorx/battleship/game/board/TrackBoard.kt
  src/main/kotlin/de/twintorx/battleship/game/cell/Cell.kt
  src/main/kotlin/de/twintorx/battleship/game/cell/Mark.kt
  src/main/kotlin/de/twintorx/battleship/game/ship/Ship.kt
  src/main/kotlin/de/twintorx/battleship/game/ship/ShipType.kt
  src/main/kotlin/de/twintorx/battleship/ui/Console.kt
  src/main/kotlin/de/twintorx/battleship/ui/Player.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/InputRegex.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/PlayerMessage.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/ServerMessage.kt
  src/main/kotlin/de/twintorx/battleship/ui/io/Writer.kt
  src/test/kotlin/de/twintorx/battleship/GameBoardTest.kt
  src/test/kotlin/de/twintorx/battleship/GameTest.kt
  src/test/kotlin/de/twintorx/battleship/InputRegexTest.kt
  src/test/kotlin/de/twintorx/battleship/TrackBoardTest.kt
Labels: release
